FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

RUN mkdir -p /usr/app/src

WORKDIR /usr/app/src

ADD ./nginx.conf /etc/nginx/
ADD ./site.conf /etc/nginx/sites-available/site.conf


EXPOSE 8002
